### ISSUE TITLE
class distribution

### ISSUE THREAD

**Issue by rimmesbe** [kidkidane/prj-rev-bwfs-dasmoto#1]
You probably don't want the header class on this div and the a-tag. Just doesn't make sense to apply the same stylings to both tags that both server very different purposes. 
Also you don't need price class on this main div. It's not a price so semantically it makes no sense.

https://github.com/kidkidane/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L9-L11

**Comment by kidkidane** [comment]
Done #1
