### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [kidkidane/prj-rev-bwfs-dasmoto#2]
You want to wrap all the related elements with the divs, not just the header tag:
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/33450763-dcda55ea-d5da-11e7-92e5-6a505ca24522.png">
This will make your code a lot more organized and easier to position/style.

https://github.com/kidkidane/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L13-L18

**Comment by kidkidane** [comment]
Done #2
