### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [kidkidane/prj-rev-bwfs-dasmoto#4]
Notice how you have to keep setting the font-family for each selector? It would be a lot easier to set the font for the page in one place. We can do this with inheritance:
html { font-family: Helvetica; }
Now all elements will inherit this font from html as their default.

https://github.com/kidkidane/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/style.css#L3

**Comment by kidkidane** [comment]
Done
